export type NigerianStateSeed = {
  code: string;
  name: string;
  capitalName: string;
  sortOrder: number;
};

export const NIGERIAN_STATE_CAPITALS: Record<string, string> = {
  AB: 'Umuahia',
  AD: 'Yola',
  AK: 'Uyo',
  AN: 'Awka',
  BA: 'Bauchi',
  BY: 'Yenagoa',
  BE: 'Makurdi',
  BO: 'Maiduguri',
  CR: 'Calabar',
  DE: 'Asaba',
  EB: 'Abakaliki',
  ED: 'Benin City',
  EK: 'Ado Ekiti',
  EN: 'Enugu',
  FC: 'Abuja',
  GO: 'Gombe',
  IM: 'Owerri',
  JI: 'Dutse',
  KD: 'Kaduna',
  KN: 'Kano',
  KT: 'Katsina',
  KE: 'Birnin Kebbi',
  KO: 'Lokoja',
  KW: 'Ilorin',
  LA: 'Ikeja',
  NA: 'Lafia',
  NI: 'Minna',
  OG: 'Abeokuta',
  ON: 'Akure',
  OS: 'Osogbo',
  OY: 'Ibadan',
  PL: 'Jos',
  RI: 'Port Harcourt',
  SO: 'Sokoto',
  TA: 'Jalingo',
  YO: 'Damaturu',
  ZA: 'Gusau',
};

export const NIGERIAN_STATES: NigerianStateSeed[] = [
  ['AB', 'Abia'],
  ['AD', 'Adamawa'],
  ['AK', 'Akwa Ibom'],
  ['AN', 'Anambra'],
  ['BA', 'Bauchi'],
  ['BY', 'Bayelsa'],
  ['BE', 'Benue'],
  ['BO', 'Borno'],
  ['CR', 'Cross River'],
  ['DE', 'Delta'],
  ['EB', 'Ebonyi'],
  ['ED', 'Edo'],
  ['EK', 'Ekiti'],
  ['EN', 'Enugu'],
  ['FC', 'Federal Capital Territory'],
  ['GO', 'Gombe'],
  ['IM', 'Imo'],
  ['JI', 'Jigawa'],
  ['KD', 'Kaduna'],
  ['KN', 'Kano'],
  ['KT', 'Katsina'],
  ['KE', 'Kebbi'],
  ['KO', 'Kogi'],
  ['KW', 'Kwara'],
  ['LA', 'Lagos'],
  ['NA', 'Nasarawa'],
  ['NI', 'Niger'],
  ['OG', 'Ogun'],
  ['ON', 'Ondo'],
  ['OS', 'Osun'],
  ['OY', 'Oyo'],
  ['PL', 'Plateau'],
  ['RI', 'Rivers'],
  ['SO', 'Sokoto'],
  ['TA', 'Taraba'],
  ['YO', 'Yobe'],
  ['ZA', 'Zamfara'],
].map(([code, name], index) => ({
  code,
  name,
  capitalName: NIGERIAN_STATE_CAPITALS[code],
  sortOrder: index + 1,
}));

export const DEFAULT_OPERATIONAL_STATE_CODE = 'LA';
