/**
 * Seeds placeholder Terms of Service / Privacy Policy content so /terms and
 * /policy are never empty. Upserts by `type`, so re-running this is safe and
 * will NOT overwrite content an admin has already edited via the Legal
 * Content settings page (only inserts when a document doesn't exist yet).
 *
 * Usage: node -r ts-node/register/transpile-only -r tsconfig-paths/register src/database/scripts/seed-legal-content.ts
 */
import dotenv from 'dotenv';
import { connectDatabase, disconnectDatabase } from '@config/data-source';
import { LegalContent } from '@models/platform/legal-content.model';

dotenv.config({ quiet: true });

const PLACEHOLDER_NOTICE = '<p><em>This is placeholder content generated to keep this page from being empty. Replace it with reviewed, legally-approved text from the admin Legal Content settings before launch.</em></p>';

const TERMS_BODY = `
${PLACEHOLDER_NOTICE}
<h2>1. Agreement to terms</h2>
<p>These Terms of Service govern your use of the Hook mobile application and website (together, "Hook", "we", "us"). By creating an account or placing an order, you agree to these terms.</p>
<h2>2. What Hook does</h2>
<p>Hook sources products from physical markets through our network of Market Associates and Hook Partners, and coordinates delivery to you. Prices, availability, and delivery times shown in the app are estimates and may change based on market conditions.</p>
<h2>3. Orders and payment</h2>
<p>All orders are subject to acceptance and product availability. Payment is processed securely through our payment partners. For orders with pay-on-delivery, you agree to be present and available at the agreed delivery location and time.</p>
<h2>4. Negotiated prices</h2>
<p>Where negotiation is available, any price you agree to through the app is binding once confirmed and will be honoured for the negotiated item and quantity within the stated validity window.</p>
<h2>5. Returns and refunds</h2>
<p>Eligible items may be returned in accordance with our Returns Policy, made available in the app. Refunds are processed to your original payment method or as store credit, depending on the circumstances.</p>
<h2>6. Account responsibilities</h2>
<p>You are responsible for maintaining the confidentiality of your account credentials and for all activity under your account. Notify us immediately of any unauthorized use.</p>
<h2>7. Prohibited conduct</h2>
<p>You agree not to misuse the platform, including attempting to interfere with its operation, submitting false information, or using the service for any unlawful purpose.</p>
<h2>8. Changes to these terms</h2>
<p>We may update these terms from time to time. Continued use of Hook after changes take effect constitutes acceptance of the revised terms.</p>
<h2>9. Contact</h2>
<p>Questions about these terms can be sent to our support team using the contact details in the app.</p>
`.trim();

const PRIVACY_BODY = `
${PLACEHOLDER_NOTICE}
<h2>1. Information we collect</h2>
<p>We collect information you provide directly (such as your name, phone number, email, and delivery address), information generated by your use of the app (such as order history and negotiation activity), and device information needed to operate the service (such as push notification tokens).</p>
<h2>2. How we use your information</h2>
<p>We use your information to process orders, facilitate delivery, communicate with you about your account and orders, improve our catalog and services, and comply with legal obligations.</p>
<h2>3. Sharing your information</h2>
<p>We share the minimum necessary information with Market Associates and Hook Partners to fulfil your order, and with payment processors to complete transactions. We do not sell your personal information.</p>
<h2>4. Data retention</h2>
<p>We retain your information for as long as your account is active and as needed to comply with legal, tax, and accounting obligations.</p>
<h2>5. Your rights</h2>
<p>You may request access to, correction of, or deletion of your personal information at any time through the app's account settings or by contacting support.</p>
<h2>6. Security</h2>
<p>We use industry-standard measures to protect your information, including encryption in transit and restricted access to sensitive data.</p>
<h2>7. Changes to this policy</h2>
<p>We may update this Privacy Policy from time to time. We will notify you of material changes through the app.</p>
<h2>8. Contact</h2>
<p>Questions about this policy can be sent to our support team using the contact details in the app.</p>
`.trim();

async function main() {
  await connectDatabase();

  const results = await Promise.all([
    LegalContent.findOneAndUpdate(
      { type: 'terms' },
      { $setOnInsert: { type: 'terms', title: 'Terms of Service', bodyHtml: TERMS_BODY, version: 1, effectiveDate: new Date() } },
      { upsert: true, returnDocument: 'after', setDefaultsOnInsert: true },
    ).lean(),
    LegalContent.findOneAndUpdate(
      { type: 'privacy' },
      { $setOnInsert: { type: 'privacy', title: 'Privacy Policy', bodyHtml: PRIVACY_BODY, version: 1, effectiveDate: new Date() } },
      { upsert: true, returnDocument: 'after', setDefaultsOnInsert: true },
    ).lean(),
  ]);

  for (const doc of results) {
    console.log(`[${doc?.type}] version ${doc?.version}, effective ${doc?.effectiveDate}`);
  }

  console.log('Legal content seed complete.');
  await disconnectDatabase();
}

main().catch((error) => {
  console.error('Legal content seed failed:', error);
  process.exitCode = 1;
});
